services:
  - type: web
    name: monero-dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn minerportal.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "minerportal.settings"
      - key: PYTHON_VERSION
        value: "3.12"
